### ISSUE TITLE
[Lontra] Finalizar Iteração I

### ISSUE THREAD

**Issue by gavelino** [ES2-UFPI/2019-2#10]
As seguinte atividades deverão ser realizadas como preparativo p/ encerramento da Sprint (Iteração I): 
*Obs1: lider, quebre atividades como julgar adequado.
*Obs2: devem ser concluídas antes de nossa próxima aula (21/out)
1. Criar Release do Produto
   - Realizar o merge com o branch master
   - Criar release no github (v0.1.0)
   - Criar Release Notes, informando quais as modificações implementadas nessa release (News, Improvements, Bug Fixes, Others).
      - Dicas de como escrever um bom release note em https://www.prodpad.com/blog/writing-release-notes/ 
   - Ao fechar essa issue, não esqueça de informar o link p/ a release na mensagem (Ajude o professor a fazer a conexão entre a atividade e os artefatos que ela gerou).
2. Preparar p/ reunião de Sprint Review (10 a 15 min a ser realizada em sala de aula, 21/out)
   - Objetivo: obter feedback sobre o Incremento do Produto desenvolvido no Sprint (inspeção e adaptação do produto);
   - Foco:  Incremento do produto, ou seja, o valor gerado para os clientes do projeto:
      - O que foi planejado? O que está sendo entregue? (Utilizar p/ isso a tabela de planejamento da iteração, quadro kanban, etc)
      - Apresentar e demonstrar os itens desenvolvidos durante o Sprint, do mais importante ao menos importante. 
   - Importante: O feedback obtido a partir da interação entre Time de Desenvolvimento, Product Owner (professor) e demais presentes na reunião de Sprint Review deve ser utilizado como matéria-prima para adicionar, remover ou modificar itens do Product Backlog. Ex: um item do sprint pode ir p/ o próximo sprint ou mesmo ser eliminado caso seja mostrado que ele não faz mais sentido.
3. **Líder**, inserir na wiki (ao final do planejamento da iteração) um quadro com a avaliação da equipe:  deve conter o nome dos integrantes, uma descrição das atividades desenvolvidas ou não por cada membro e uma pontuação. A pontuação será utilizada p/ normalizar a nota de cada integrante. Cada grupo tem n pontos, onde n é o número de integrantes. O líder deve distribuir esses n pontos pelos n integrantes. Assim, se todos tiverem trabalhado igualmente, todos receberão 1 ponto  e dessa forma, todos receberão a mesma nota. Valores inferiores ou superiores a 1 irão, respectivamente, penalizar ou bonificar o integrante.

**Comment by ianAraujj** [comment]
https://github.com/ES2-UFPI/Lontra/releases
